#!/usr/bin/env ruby

require File.dirname(__FILE__) + '/../lib/initrb'

PATH="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"
DESC="nginx daemon"
NAME="nginx"
DAEMON="/usr/local/sbin/#{NAME}"
CONFIGFILE="/etc/nginx/nginx.conf"
PIDFILE="/var/run/#{NAME}.pid"
SCRIPTNAME="/etc/init.d/#{NAME}"

Initrb.run